services:
  db:
    container_name: mail0-db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mail0
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mail0:
    depends_on:
      - db
    build: .
    container_name: mail0-interface
    image: node:22-slim
    restart: always
    env_file: .env
    ports:
      - "3000:3000"

volumes:
  postgres-data:
